// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.keyboardevent.keypress.hack.use_legacy_keycode_and_charcode", "powerpoint.officeapps.live.com");
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "65ab3314-6b45-4304-b74a-2b6cb3feea9f");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1553651114);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1553651083);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"35985\":1553651085790,\"35987\":1553651085790,\"35993\":1553651085790}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"788\":[1553651085801,1553651086223]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{5fd55264-e54e-4df5-b3db-5554f67afdaa}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1553576400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1553651095070");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1553652885070");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1553651087869");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1553654687869");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1553651085");
user_pref("browser.slowStartup.averageTime", 75001);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190322095656");
user_pref("browser.startup.homepage_override.mstone", "66.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"jid1-niffy2ca8fy1tg_jetpack-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"jid1-niffy2ca8fy1tg_jetpack-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1553651086307");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "a4d3e2b799ff41799da0163bf7855f56");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "66.0.1");
user_pref("extensions.lastPlatformVersion", "66.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-NIfFY2CA8fy1tg@jetpack", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"b87ce91a-6f4a-4054-95a2-a8074e75d548\",\"screenshots@mozilla.org\":\"864d72ac-d20d-43ec-883d-c649deaded26\",\"webcompat-reporter@mozilla.org\":\"6efacbdc-1b6e-4e38-892d-915a0f914c20\",\"webcompat@mozilla.org\":\"bbec7a84-9a03-40a6-8971-be34f8c9e385\",\"jid1-NIfFY2CA8fy1tg@jetpack\":\"ee9c773a-a6b8-4874-984a-ba770f15a499\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "de951d9d-1c2d-4d16-ae68-323917f81116");
user_pref("security.sandbox.plugin.tempDirSuffix", "de6bd8ac-b804-40f1-9e5e-edb9dddfa7fa");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1553651082);
user_pref("toolkit.telemetry.cachedClientID", "f2641256-9073-441d-a339-8f64490bbc10");
user_pref("toolkit.telemetry.previousBuildID", "20190322095656");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
